Add test for ubuntu

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -7,7 +7,7 @@ on:
   pull_request:
 
 jobs:
-  build:
+  build_without_convert:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
@@ -21,6 +21,60 @@ jobs:
         run: |
           ./vista-fonts-installer.sh
 
-      # - name: Test if directory is created with desired fonts
-      #   run: |
-      #     TODO ...
+      - name: Test if directory is created with desired fonts
+        run: |
+          testfile=tests/expected-files-ubuntu-raw.txt
+          export INSTALLED_PATH=/usr/share/fonts/truetype/vista
+          echo -n "" > result.txt
+          while IFS= read -r line
+          do
+            echo "$line"
+            if [ -f "$INSTALLED_PATH/$line" ]; then
+              echo "$INSTALLED_PATH/$line @ PASS" >> result.txt
+            else
+              echo "$INSTALLED_PATH/$line @ FAIL" >> result.txt
+            fi
+          done < "$testfile"
+          if [ "0" == "$(grep -v FAIL result.txt | wc -l | tr -d ' ')" ]; then
+            echo "At least one font file not being installed, see output:"
+            cat result.txt
+            exit 1
+          fi
+
+
+  build_with_convert:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@master
+
+      - name: Install prerequisite packages
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl cabextract fontforge
+
+      - name: Run script
+        env:
+          CONVERT_TTF: true
+          MS_FONT_PATH: fonts
+        run: |
+          ./vista-fonts-installer.sh
+
+      - name: Test if directory is created with desired fonts
+        run: |
+          testfile=tests/expected-files-ubuntu-converted.txt
+          export INSTALLED_PATH=fonts
+          echo -n "" > result.txt
+          while IFS= read -r line
+          do
+            echo "$line"
+            if [ -f "$INSTALLED_PATH/$line" ]; then
+              echo "$INSTALLED_PATH/$line @ PASS" >> result.txt
+            else
+              echo "$INSTALLED_PATH/$line @ FAIL" >> result.txt
+            fi
+          done < "$testfile"
+          if [ "0" == "$(grep -v FAIL result.txt | wc -l | tr -d ' ')" ]; then
+            echo "At least one font file not being installed, see output:"
+            cat result.txt
+            exit 1
+          fi
